include(${torchlight_dir}/test/unittest/Collections/List.cmake)
include(${torchlight_dir}/test/unittest/Collections/Iterator.cmake)
include(${torchlight_dir}/test/unittest/Collections/String.cmake)
include(${torchlight_dir}/test/unittest/Collections/Bytes.cmake)
include(${torchlight_dir}/test/unittest/Collections/Integer.cmake)
include(${torchlight_dir}/test/unittest/Collections/Decimal.cmake)
include(${torchlight_dir}/test/unittest/Collections/Map.cmake)