include_directories(${tensorslow_dir}/src)
message(STATUS "tensorslow_frontend_files: " ${tensorslow_frontend_files})
include(${tensorslow_dir}/src/Generation/Generation.cmake)
include(${tensorslow_dir}/src/Collections/Collections.cmake)
include(${tensorslow_dir}/src/Object/Object.cmake)
include(${tensorslow_dir}/src/Runtime/Runtime.cmake)
include(${tensorslow_dir}/src/ByteCode/ByteCode.cmake)
include(${tensorslow_dir}/src/Function/Function.cmake)
include(${tensorslow_dir}/src/IR/IR.cmake)
include(${tensorslow_dir}/src/Backend/Backend.cmake)
include(${tensorslow_dir}/src/Tools/Tools.cmake)
include(${tensorslow_dir}/src/Frontend/Frontend.cmake)
include(${tensorslow_dir}/src/Engine/Engine.cmake)