include_directories(${torchlight_dir}/src)
message(STATUS "torchlight_frontend_files: " ${torchlight_frontend_files})
include(${torchlight_dir}/src/Generation/Generation.cmake)
include(${torchlight_dir}/src/Collections/Collections.cmake)
include(${torchlight_dir}/src/Object/Object.cmake)
include(${torchlight_dir}/src/Runtime/Runtime.cmake)
include(${torchlight_dir}/src/ByteCode/ByteCode.cmake)
include(${torchlight_dir}/src/Function/Function.cmake)
include(${torchlight_dir}/src/Ast/Ast.cmake)
include(${torchlight_dir}/src/Backend/Backend.cmake)
include(${torchlight_dir}/src/Tools/Tools.cmake)
include(${torchlight_dir}/src/Frontend/Frontend.cmake)
include(${torchlight_dir}/src/Compiler/Compiler.cmake)